#!/bin/sh
#

if [ "$3" = "/" ]; then
  if [ -e /Library/LaunchDaemons/com.github.managedmac-managedprinters-check.plist ]; then
  launchctl unload /Library/LaunchDaemons/com.github.managedmac-managedprinters-check.plist
fi

exit 0
